/*
 * VE301
 *
 * Copyright (C) 2024 LJunkie <christoph.pickart@gmx.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see <https://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ljunkie_ve301_MenuControl */

#ifndef _Included_org_ljunkie_ve301_MenuControl
#define _Included_org_ljunkie_ve301_MenuControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_ctrl_new
 * Signature: (IIIIIIDLjava/lang/String;ILorg/ljunkie/ve301/MenuItemListener;Lorg/ljunkie/ve301/MenuControlListener;)J
 */
JNIEXPORT jlong JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1ctrl_1new
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jdouble, jstring, jint, jobject, jobject);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_loop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1loop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_ctrl_get_root
 * Signature: (J)Lorg/ljunkie/ve301/Menu;
 */
JNIEXPORT jobject JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1ctrl_1get_1root
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_set_style
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1set_1style
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    get_active_menu
 * Signature: (J)Lorg/ljunkie/ve301/Menu;
 */
JNIEXPORT jobject JNICALL Java_org_ljunkie_ve301_MenuControl_get_1active_1menu
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_ctrl_quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1ctrl_1quit
  (JNIEnv *, jobject, jlong menu_ctrl_handle);

#ifdef __cplusplus
}
#endif
#endif
