/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ljunkie_ve301_Menu */

#ifndef _Included_org_ljunkie_ve301_Menu
#define _Included_org_ljunkie_ve301_Menu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    menu_new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ljunkie_ve301_Menu_menu_1new
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    menu_add_sub_menu
 * Signature: (JLjava/lang/String;J)Lorg/ljunkie/ve301/MenuItem;
 */
JNIEXPORT jobject JNICALL Java_org_ljunkie_ve301_Menu_menu_1add_1sub_1menu
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    get_menu_control
 * Signature: (J)Lorg/ljunkie/ve301/MenuControl;
 */
JNIEXPORT jobject JNICALL Java_org_ljunkie_ve301_Menu_get_1menu_1control
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    menu_open
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_Menu_menu_1open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    menu_get_active_id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ljunkie_ve301_Menu_menu_1get_1active_1id
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    menu_set_transient
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_Menu_menu_1set_1transient
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_ljunkie_ve301_Menu
 * Method:    menu_get_transient
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ljunkie_ve301_Menu_menu_1get_1transient
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
