/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ljunkie_ve301_MenuControl */

#ifndef _Included_org_ljunkie_ve301_MenuControl
#define _Included_org_ljunkie_ve301_MenuControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_ctrl_new
 * Signature: (IIIIIIDLjava/lang/String;ILorg/ljunkie/ve301/MenuItemListener;Lorg/ljunkie/ve301/MenuControlListener;)J
 */
JNIEXPORT jlong JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1ctrl_1new
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jdouble, jstring, jint, jobject, jobject);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_loop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1loop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_ctrl_get_root
 * Signature: (J)Lorg/ljunkie/ve301/Menu;
 */
JNIEXPORT jobject JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1ctrl_1get_1root
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_set_style
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1set_1style
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    get_active_menu
 * Signature: (J)Lorg/ljunkie/ve301/Menu;
 */
JNIEXPORT jobject JNICALL Java_org_ljunkie_ve301_MenuControl_get_1active_1menu
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuControl
 * Method:    menu_ctrl_quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuControl_menu_1ctrl_1quit
  (JNIEnv *, jobject, jlong menu_ctrl_handle);

#ifdef __cplusplus
}
#endif
#endif
