/*
 * VE301
 *
 * Copyright (C) 2024 LJunkie <christoph.pickart@gmx.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see <https://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ljunkie_ve301_MenuItem */

#ifndef _Included_org_ljunkie_ve301_MenuItem
#define _Included_org_ljunkie_ve301_MenuItem
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ljunkie_ve301_MenuItem_UNKNOWN_OBJECT_TYPE
#define org_ljunkie_ve301_MenuItem_UNKNOWN_OBJECT_TYPE -1L
#undef org_ljunkie_ve301_MenuItem_OBJECT_TYPE_ACTION
#define org_ljunkie_ve301_MenuItem_OBJECT_TYPE_ACTION -2L
/*
 * Class:     org_ljunkie_ve301_MenuItem
 * Method:    menu_item_update_label
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuItem_menu_1item_1update_1label
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_ljunkie_ve301_MenuItem
 * Method:    menu_item_new
 * Signature: (JLjava/lang/String;JILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_ljunkie_ve301_MenuItem_menu_1item_1new
  (JNIEnv *, jobject, jlong, jstring, jlong, jint, jstring, jint);

/*
 * Class:     org_ljunkie_ve301_MenuItem
 * Method:    menu_item_set_listener
 * Signature: (JLorg/ljunkie/ve301/MenuItemListener;)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuItem_menu_1item_1set_1listener
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_ljunkie_ve301_MenuItem
 * Method:    menu_item_warp_to
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuItem_menu_1item_1warp_1to
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuItem
 * Method:    menu_item_show
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_MenuItem_menu_1item_1show
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ljunkie_ve301_MenuItem
 * Method:    is_sub_menu
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ljunkie_ve301_MenuItem_is_1sub_1menu
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
