/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ljunkie_ve301_Application */

#ifndef _Included_org_ljunkie_ve301_Application
#define _Included_org_ljunkie_ve301_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ljunkie_ve301_Application
 * Method:    init_application
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_ljunkie_ve301_Application_init_1application
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
